project/core/views.py
from project import app
from flask import render_template, request, Blueprint
from project.models import BlogPost

core = Blueprint("core", __name__)


@core.route("/")
def index():
    page = request.args.get("page", 1, int)
    with app.app_context():
        posts = BlogPost.query.order_by(BlogPost.created_at.desc()).paginate(
            page=page, per_page=5
        )
        # posts.iter_pages()
        return render_template("index.html", posts=posts)


@core.route("/info")
def info():
    return render_template("info.html")

project/posts/views.py
"""
For BlogPosts
- Create
- View
- Edit
- Delete
"""

from flask import abort, flash, redirect, render_template, Blueprint, request, url_for
from flask_login import current_user, login_required
from project import db, app
from project.models import BlogPost
from project.posts.forms import BlogPostForm

blog_posts = Blueprint("blog_posts", __name__)


@blog_posts.route("/create", methods=["GET", "POST"])
@login_required
def create():
    form = BlogPostForm()
    if form.validate_on_submit():
        blog_post = BlogPost(
            title=form.title.data, text=form.text.data, user_id=current_user.id # type: ignore
        )
        with app.app_context():
            db.session.add(blog_post)
            db.session.commit()
        flash("Blog Post Created!", "success")
        return redirect(url_for("core.index"))
    return render_template("create_post.html", form=form)


@blog_posts.route("/posts/<int:blog_post_id>")
def view(blog_post_id):
    with app.app_context():
        blog_post = BlogPost.query.get_or_404(blog_post_id, "Post not found.")
        author = blog_post.author
    return render_template("view_post.html", post=blog_post, author=author)


@blog_posts.route("/posts/<int:blog_post_id>/update", methods=["GET", "POST"])
@login_required
def update(blog_post_id):
    with app.app_context():
        blog_post: BlogPost = BlogPost.query.get_or_404(blog_post_id, "Post not found.")
        author = blog_post.author
        if author.id != current_user.id: # type: ignore
            flash("Only the author can edit the post.", "danger")
            abort(403)
        form = BlogPostForm()
        if form.validate_on_submit():
            blog_post.title = form.title.data # type: ignore
            blog_post.text = form.text.data # type: ignore
            db.session.commit()
            flash("Blog post updated successfully.", "success")
            return redirect(url_for("blog_posts.view", blog_post_id=blog_post_id))
        elif request.method == "GET":
            form.title.data = blog_post.title
            form.text.data = blog_post.text
    return render_template("create_post.html", form=form)


@blog_posts.route("/posts/<int:blog_post_id>/delete", methods=["GET", "POST"])
@login_required
def delete(blog_post_id):
    with app.app_context():
        blog_post: BlogPost = BlogPost.query.get_or_404(blog_post_id, "Post not found.")
        author = blog_post.author
        if author.id != current_user.id: # type: ignore
            flash("Only the author can delete the post.", "danger")
            abort(403)
        db.session.delete(blog_post)
        db.session.commit()
        flash("Post deleted successfully.", "success")
    return redirect(url_for("core.index"))

project/users/views.py
"""
Views needed:
- Register
- Login
- Logout
- Account
- Update
- User's Blogpost
"""

from flask import (
    flash,
    render_template,
    redirect,
    Blueprint,
    request,
    url_for,
)
from flask_login import login_user, current_user, logout_user, login_required
from project import app, db
from flask_wtf.file import FileStorage
from project.models import User, BlogPost
from project.users.forms import LoginForm, RegistrationForm, UpdateForm
from project.users.picture_handler import add_profile_pic

users = Blueprint("users", __name__)


@users.route("/register", methods=["GET", "POST"])
def register():
    """
    The `register` function handles the registration process for new users, including form validation
    and database insertion.
    :return: the rendered template "register.html" along with the form object.
    """
    form = RegistrationForm()
    if form.validate_on_submit():
        user = User(
            email=form.email.data,
            username=form.username.data,
            password=form.password.data,
        )
        with app.app_context():
            db.session.add(user)
            db.session.commit()
        flash("Thanks for your registration!", "success")
        return redirect(url_for("users.login"))
    return render_template("register.html", form=form)


@users.route("/login", methods=["GET", "POST"])
def login():
    """
    The function `login()` handles the login process by validating the login form, checking if the user
    exists and the password is correct, and then logging in the user if the credentials are valid.
    :return: a rendered template for the login page, with the login form passed as a parameter.
    """
    form = LoginForm()
    if form.validate_on_submit():
        with app.app_context():
            user = User.query.filter_by(email=form.email.data).first()
        if not user:
            form.password.data = ""
            form.email.data = ""
            flash("The email is not registered.", "warning")
            return render_template("login.html", form=form)
        if user.check_password(form.password.data):
            login_user(user)
            flash(f"Loged in as {user.username}.", "success")
            next = request.args.get("next")
            if next == None or not next[0] == "/":
                next = url_for("core.index")
            return redirect(next)
        else:
            flash("Invalid password.", "danger")
            return render_template("login.html", form=form)
    return render_template("login.html", form=form)


@users.route("/acount")
@login_required
def account():
    """
    The function `account()` renders the account.html template with the current user's information and
    profile image.
    :return: the rendered template "account.html" with the variables "user" and "profile_img".
    """
    user: User = current_user # type: ignore
    profile_img = url_for("static", filename="profile_imgs/" + user.profile_img)
    return render_template("account.html", user=user, profile_img=profile_img)


@users.route("/update", methods=["GET", "POST"])
@login_required
def update():
    """
    The `update()` function handles the updating of user account information, including the profile
    picture, username, and email.
    :return: a response object that redirects the user to a specific route. The route depends on the
    outcome of the form validation and updates. If the form is not valid or there are no updates to be
    made, the user is redirected to the "users.update" route. If the form is valid and updates are made,
    the user is redirected to the "users.account" route.
    """
    form = UpdateForm()
    if form.validate_on_submit():
        if not form.any_updates(user=current_user): # type: ignore
            flash("Nothing to update.", "warning")
            return redirect(url_for("users.update"))
        updated = []
        with app.app_context():
            user = User.query.filter_by(email=current_user.email).first() # type: ignore
            if form.picture.data:
                pic: FileStorage = add_profile_pic(form.picture.data, user.username) # type: ignore
                user.profile_img = pic # type: ignore
                updated.append("profile picture")
            if form.username.data and form.username.data != user.username: # type: ignore
                user.username = form.username.data # type: ignore
                updated.append("username")
            if form.email.data and form.email.data != user.email: # type: ignore
                user.email = form.email.data # type: ignore
                updated.append("email")
            app.logger.info("Commiting changes")
            db.session.commit()
        flash(f"Account updated succesfully. Updated {', '.join(updated)}.", "success")
        return redirect(url_for("users.account"))
    elif request.method == "GET":
        form.username.data = current_user.username # type: ignore
        form.email.data = current_user.email # type: ignore
    return render_template("update.html", form=form)


@users.route("/<username>")
# @login_required
def posts(username: str):
    """
    The `posts` function retrieves and paginates blog posts written by a specific user and renders them
    on a template.
    
    :param username: The `username` parameter is the username of the user whose posts you want to
    retrieve
    :return: a rendered template called "user_posts.html" with the variables "posts" and "user" passed
    to it.
    """
    page = request.args.get("page", 1, int)
    with app.app_context():
        user = User.query.filter_by(username=username).first_or_404()
        posts = (
            BlogPost.query.filter_by(author=user)
            .order_by(BlogPost.created_at.desc())
            .paginate(page=page, per_page=5)
        )
        print(posts.first, posts.has_next, posts.has_prev, flush=True)
        return render_template("user_posts.html", posts=posts, user=user)


@users.route("/logout")
@login_required
def logout():
    """
    The `logout` function logs out the current user, flashes a message indicating the user has been
    logged out, and redirects them to the index page.
    :return: a redirect to the "core.index" route.
    """
    flash(f"You have been logged out from {current_user.username}.", "info") # type: ignore
    logout_user()
    return redirect(url_for("core.index"))

project/templates/TEMP.html
{% extends 'base.html' %}
{% block title %}
    
{% endblock %}
{% block content %}
    
{% endblock %}

project/templates/account.html
{% extends 'base.html' %}
{% block title %}
Account
{% endblock %}
{% block content %}
<div class="container">
    <div class="jumbotron text-center">
        <img src="{{profile_img}}" alt="Profile Image" width="200px" height="200px">
        <div class="card-body">
            <h4 class="card-title">@{{user.username}}</h4>
            <h6 class="card-subtitle mb-2 text-muted">Member since {{ user.created_at.date() }}</h6>
            <p class="card-text">{{user.email}}</p>
            <a href="/{{user.username}}" class="card-link">User Posts</a>
            <a href="{{url_for('users.update')}}" class="card-link">Update Profile</a>
        </div>
    </div>
</div>
{% endblock %}

project/templates/base.html
<!doctype html>
<html lang="en">

<head>
    <title> PuppyBlog - {% block title %}{% endblock %}</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.1/css/all.css"
        integrity="sha384-O8whS3fhG2OnA5Kas0Y9l3cfpmYjapjI0E4theH4iuMD+pLhbf6JI0jIMfYcK3yZ" crossorigin="anonymous">
    <script defer src="https://use.fontawesome.com/releases/v5.1.1/js/all.js"
        integrity="sha384-BtvRZcyfv4r0x/phJt9Y9HhnN5ur1Z+kZbKVgzVBAlQZX4jvAuImlIz+bG7TS00a"
        crossorigin="anonymous"></script>
</head>

<body>
    <!-- Navigator -->
    <nav class="navbar navbar-expand-sm navbar-dark bg-primary">
        <a class="navbar-brand" href="{{url_for('core.index')}}">PuppyBlog</a>
        <button class="navbar-toggler d-lg-none" type="button" data-toggle="collapse" data-target="#collapsibleNavId"
            aria-controls="collapsibleNavId" aria-expanded="false" aria-label="Toggle navigation"></button>
        <div class="collapse navbar-collapse" id="collapsibleNavId">
            <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                <li class="nav-item active">
                    <a class="nav-link" href="{{url_for('core.info')}}">About Us</a>
                </li>
                <!-- If Logged -->
                {% if current_user.is_authenticated %}

                <li class="nav-item active">
                    <a class="nav-link" href="{{url_for('blog_posts.create')}}">Create Post</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{{url_for('users.logout')}}">Log Out</a>
                </li>
                <!-- <li class="nav-item active align-self-end"></li>
                    <a class="nav-link" href="{{url_for('users.account')}}">{{ current_user.username }}</a>
                </li> -->
                <!-- If NOT Logged -->
                {% else %}
                <li class="nav-item active">
                    <a class="nav-link " href="{{url_for('users.login')}}">Log In</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{{url_for('users.register')}}">Register</a>
                </li>
                {% endif %}
            </ul>
            <ul class="navbar-nav  mt-2 mt-lg-0" style="margin-right: 40px;">
                <li class="nav-item active" >
                    <a class="nav-link h5 mb-0" href="{{url_for('users.account')}}"><strong>{{ current_user.username }}</strong></a>
                </li>
            </ul>
        </div>
    </nav>
    <!-- Flash Messages -->
    {% for alert in get_flashed_messages(with_categories= True) %}
    {% if alert[0] == "success" %}
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        <strong><i class="fa fa-check" aria-hidden="true"></i> Success! </strong> {{ alert[1] }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    {% elif alert[0] == "warning" %}
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
        <strong><i class="fas fa-wind-warning"></i> Something went wrong! </strong> {{ alert[1] }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    {% elif alert[0] == "danger" %}
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <strong><i class="fas fa-diagnoses    "></i> Error! </strong> {{ alert[1] }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    {% else %}
    <div class="alert alert-info alert-dismissible fade show" role="alert">
        <strong>Info: </strong> {{ alert[1] }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    {% endif %}
    {% endfor %}

    {% block content %}
    {% endblock %}
</body>

</html>

project/templates/create_post.html
{% extends 'base.html' %}
{% block title %}
Create Post
{% endblock %}
{% block content %}
<div class="container">
    <div class="jumbotron">
        <h1 class="display-4">Post Editor.</h1>
        <hr class="my-2">
        <div class="container">
            <form action="" method="post">
                {{ form.hidden_tag() }}
                <div class="form-group">
                    {{ form.title(class="form-control form-control-lg", placeholder="Title") }}
                </div>
                <hr>
                <div class="form-group">
                    {{ form.text(class="form-control form-control-lg", placeholder="Post content.", rows="5") }}
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-primary">Post</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

project/templates/index.html
{% extends 'base.html' %}
{% block title %}
Home
{% endblock %}
{% block content %}
<!-- Heading -->
<div class="container">
  <div class="jumbotron" style="margin-bottom: 20px; padding-bottom: 20px;">
    <h1 class="display-4">Puppy Company Blog</h1>
    <p class="lead">Welcome to our blog. Here you can share any information about your little friends and know people
      that share your love for puppies.</p>
  </div>
</div>

<!-- Posts -->
<div class="card container" style="width: 75%;">
    <h2 style="text-align: center; padding-top: 3vh;">Recent Posts</h2>
    <hr class="my-2">
  {% for post in posts.items%}
  <div class="card-body " style="margin-bottom: 10px; padding-top: 30px; padding-bottom: 20px;">
    <div style="display: flex; justify-content: space-between;">
      <div>
        <h4><a href="{{url_for('blog_posts.view', blog_post_id = post.id)}}">{{post.title}}</a></h4>
        <p class="lead">By <a href="{{url_for('users.posts', username = post.author.username)}}">
            @{{ post.author.username }}
          </a>
        </p>
        <p class="text-muted">Created at {{ post.created_at.strftime('%a %d %b %Y') }}.</p>
      </div>
      <div>
        <img style="height: 100px; width: auto;" src="{{url_for('static', filename='profile_imgs/'+post.author.profile_img)}}" alt="Profile Image">
      </div>
    </div>
    <hr class="my-2">
    <p>{{ post.text }}</p>
  </div>
  {% endfor %}
</div>

<!-- Paginator -->
<nav aria-label="Page navigation">
  <ul class="pagination justify-content-center">
    {% if posts.has_prev %}
    <li class="page-item">
      {% else %}
    <li class="page-item disabled">
      {% endif %}
      <a class="page-link" href="{{url_for('core.index', page=posts.page - 1)}}" aria-label="Previous">
        <span aria-hidden="true">&laquo;</span>
        <span class="sr-only">Previous</span>
      </a>
    </li>
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
    {% if page_num == posts.page %}
    <li class="page-item disabled">
      {% else %}
    <li class="page-item">
      {% endif %}
      <a class="page-link" href="{{url_for('core.index', page=page_num)}}">{{page_num}}</a>
    </li>
    {% endfor %}
    {% if posts.has_next %}
    <li class="page-item">
      {% else %}
    <li class="page-item disabled">
      {% endif %}
      <a class="page-link" href="{{url_for('core.index', page=posts.page + 1)}}" aria-label="Next">
        <span aria-hidden="true">&raquo;</span>
        <span class="sr-only">Next</span>
      </a>
    </li>
  </ul>
</nav>
{% endblock %}

project/templates/info.html
{% extends 'base.html' %}
{% block title %}
About Us
{% endblock %}
{% block content %}
<div class="container">
    <div class="jumbotron">
        <h1 class="display-4">About Us</h1>
        <p class="lead">{{ lipsum(n=5, html=True, min=20, max=100) }}</p>
    </div>
</div>
{% endblock %}

project/templates/login.html
{% extends 'base.html' %}
{% block title %}
Log In
{% endblock %}
{% block content %}
<div class="container">
    <div class="jumbotron">
        <h1 class="display-4">Log In</h1>
        <hr>
        <form method="POST">
            {{ form.hidden_tag() }}
            <div class="form-row">
                <div class="form-group col-md-6">
                    {{ form.email(class="form-control", placeholder = "Email") }}
                </div>
                <div class="form-group col-md-6">
                    {{ form.password(class="form-control", placeholder = "Password") }}
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-6">
                    <p class="lead">
                        {{ form.submit(class="btn btn-primary btn-lg") }}
                    </p>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}

project/templates/register.html
{% extends 'base.html' %}
{% block title %}
Register
{% endblock %}
{% block content %}
<div class="container">
    <div class="jumbotron">
        <h1 class="display-4">Register!</h1>
        <hr>
        <form method="POST">
            {{ form.hidden_tag() }}
            <div class="form-row">
                <div class="form-group col-md-6">
                    {{ form.email(class="form-control", placeholder = "Email") }}
                </div>
                <div class="form-group col-md-6">
                    <div class="input-group mb-2">
                        <div class="input-group-prepend">
                            <div class="input-group-text">@</div>
                        </div>
                        {{ form.username(class="form-control", placeholder = "username") }}
                    </div>
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-6">
                    {{ form.password(class="form-control", placeholder = "Password") }}
                </div>
                <div class="form-group col-md-6">
                    {{ form.password_confirm(class="form-control", placeholder = "Confirm Password") }}
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-6">
                    <p class="lead">
                        {{ form.submit(class="btn btn-primary btn-lg") }}
                    </p>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}

project/templates/update.html
{% extends 'base.html' %}
{% block title %}
Update Account
{% endblock %}
{% block content %}
<div class="container">
    <div class="jumbotron">
        <h1 class="display-3">Update Acount</h1>
        <p class="lead">Change your account information.</p>
        <hr class="my-2">
        <form method="POST" action="" enctype="multipart/form-data">
            {{ form.hidden_tag() }}
            <div class="form-row">
                <div class="form-group col-md-6">
                    {{ form.email(class="form-control", placeholder = "Email") }}
                </div>
                <div class="form-group col-md-6">
                    <div class="input-group mb-2">
                        <div class="input-group-prepend">
                            <div class="input-group-text">@</div>
                        </div>
                        {{ form.username(class="form-control", placeholder = "username") }}
                    </div>
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-6">
                    <div class="custom-file">
                        {{ form.picture(class="custom-file-input") }}
                        {{ form.picture.label(class="custom-file-label", text=form.picture.data ) }}
                    </div>
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-6">
                    <p class="lead">
                        {{ form.submit(class="btn btn-primary btn-lg") }}
                    </p>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}

project/templates/user_posts.html
{% extends 'base.html' %}
{% block title %}
{{ user.username }}'s Posts
{% endblock %}
{% block content %}
<div class="container">
    <div class="jumbotron text-center" style="padding-bottom: 3rem;">
        <h1 class="display-4">@{{ user.username }}'s Posts</h1>
        <img src="{{ url_for('static', filename= 'profile_imgs/' + user.profile_img) }}" alt="Profile Image">
    </div>
</div>

<!-- Posts -->
<div class="card container" style="width: 75%;">
  {% for post in posts.items%}
  <div class="card-body " style="margin-bottom: 10px; padding-top: 30px; padding-bottom: 20px;">
    <div style="display: flex; justify-content: space-between;">
      <div>
        <h4><a href="{{url_for('blog_posts.view', blog_post_id = post.id)}}">{{post.title}}</a></h4>
        <p class="lead">By <a href="{{url_for('users.posts', username = post.author.username)}}">
            @{{ post.author.username }}
          </a>
        </p>
        <p class="text-muted">Created at {{ post.created_at.strftime('%a %d %b %Y') }}.</p>
      </div>
      <div>
        <img style="height: 100px; width: auto;" src="{{url_for('static', filename='profile_imgs/'+post.author.profile_img)}}" alt="Profile Image">
      </div>
    </div>
    <hr class="my-2">
    <p>{{ post.text }}</p>
  </div>
  {% endfor %}
</div>

<!-- Paginator -->
<nav aria-label="Page navigation">
  <ul class="pagination justify-content-center">
    {% if posts.has_prev %}
    <li class="page-item">
      {% else %}
    <li class="page-item disabled">
      {% endif %}
      <a class="page-link" href="{{url_for('core.index', page=posts.page - 1)}}" aria-label="Previous">
        <span aria-hidden="true">&laquo;</span>
        <span class="sr-only">Previous</span>
      </a>
    </li>
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
    {% if page_num == posts.page %}
    <li class="page-item disabled">
      {% else %}
    <li class="page-item">
      {% endif %}
      <a class="page-link" href="{{url_for('core.index', page=page_num)}}">{{page_num}}</a>
    </li>
    {% endfor %}
    {% if posts.has_next %}
    <li class="page-item">
      {% else %}
    <li class="page-item disabled">
      {% endif %}
      <a class="page-link" href="{{url_for('core.index', page=posts.page + 1)}}" aria-label="Next">
        <span aria-hidden="true">&raquo;</span>
        <span class="sr-only">Next</span>
      </a>
    </li>
  </ul>
</nav>
{% endblock %}

project/templates/view_post.html
{% extends 'base.html' %}
{% block title %}
{{ post.title }}
{% endblock %}
{% block content %}
<div class="container">
    <div class="jumbotron">
        <h1 class="display-4">{{post.title}}</h1>
        <div>
            <p class="lead">Written by <a href="{{url_for('users.posts', username=author.username)}}">
                    @{{ author.username}}
                </a></p>
            <p>Created at {{ post.created_at.strftime('%a %d %b %Y') }}</p>
        </div>
        {% if author == current_user %}
        <div>
            <a class="btn btn-primary" href="{{url_for('blog_posts.update', blog_post_id = post.id)}}"
                role="button">Edit</a>
            <!-- Button trigger modal -->
            <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#deletePostModal">
                Delete
            </button>
            <!-- Modal -->
            <div class="modal fade" id="deletePostModal" tabindex="-1" role="dialog" aria-labelledby="Delete Post"
                aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title">Delete Post</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <div class="container-fluid">
                                Are you sure that you want to delete this post?
                            </div>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                            <a class="btn btn-danger" href="{{url_for('blog_posts.delete', blog_post_id=post.id)}}" role="button">Delete</a>
                        </div>
                    </div>
                </div>
            </div>

            <script>
                $('#exampleModal').on('show.bs.modal', event => {
                    var button = $(event.relatedTarget);
                    var modal = $(this);
                    // Use above variables to manipulate the DOM

                });
            </script>
        </div>
        {% endif %}
        <hr class="my-2">
        <p>{{ post.text }}</p>
    </div>
</div>
{% endblock %}